export const Player_Event_Types = {
  STATE_CHANGE: "STATE_CHANGE",
  TIME_UPDATE: "TIME_UPDATE",
  VOLUME_CHANGE: "VOLUME_CHANGE",
  SPEED_CHANGE: "SPEED_CHANGE",
};

export enum PLAYER_STATES {
  PLAYING,
  PAUSED,
}
